### ISSUE TITLE
[Ques] : 如何生成Image_Resource里的bin文件

### ISSUE THREAD

**Issue by RoyRobin** [nixlong/GR5526-Smart-Watch#5]
如何生成Image_Resource里的bin文件？是否有工具可以直接生成bin和对应的c和h？

**Comment by nixlong** [comment]
> 如何生成Image_Resource里的bin文件？是否有工具可以直接生成bin和对应的c和h？

有现成工具批量化生成 bin 的, 后续我们把工具放在 Github 上

**Comment by nixlong** [comment]
> 如何生成Image_Resource里的bin文件？是否有工具可以直接生成bin和对应的c和h？

当前可以从如下链接下载:

[点我跳转](https://developers.goodix.com/zh/bbs/blog_detail/2996e8f9f352491eb0ccca468f28f2ce)

**Comment by RoyRobin** [comment]
好的，十分感谢，已解决
